#!/usr/bin/env bash
# Kelan Security — Release helper
#
# Bumps version in all crates, runs build + tests, commits, tags, and
# optionally pushes to trigger the GitHub Actions release pipeline.
#
# Usage:
#   ./scripts/release.sh 0.3.0
#   ./scripts/release.sh 0.3.0-beta.1
#
set -euo pipefail

VERSION="${1:-}"
[ -z "$VERSION" ] && { echo "Usage: $0 <version>  e.g. $0 0.3.0"; exit 1; }

# ── Validate semver (x.y.z or x.y.z-pre.release)
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'; then
  echo "ERROR: Invalid version '${VERSION}'. Use semver: 1.2.3 or 1.2.3-beta.1"
  exit 1
fi

TAG="v${VERSION}"

echo ""
echo "=== Kelan Security Release — ${TAG} ==="
echo ""

# ── Pre-flight checks
git diff --quiet          || { echo "ERROR: Uncommitted changes detected. Commit or stash first."; exit 1; }
git diff --cached --quiet || { echo "ERROR: Staged changes detected. Commit first."; exit 1; }

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "main" ]; then
  echo "WARNING: Not on 'main' (current branch: ${BRANCH})"
  read -r -p "Continue anyway? [y/N] " CONTINUE
  [[ "$CONTINUE" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# ── Check tag doesn't already exist
if git tag | grep -q "^${TAG}$"; then
  echo "ERROR: Tag ${TAG} already exists locally. Delete it first: git tag -d ${TAG}"
  exit 1
fi

# ── Bump version in Cargo.toml files
echo "Bumping version to ${VERSION}..."
CRATES=(
  "aitp-server/Cargo.toml"
  "aitp-client/Cargo.toml"
  "aitp-sdk/Cargo.toml"
  "aitp-core/Cargo.toml"
  "aitp-identity/Cargo.toml"
  "aitp-ai-engine/Cargo.toml"
  "aitp-control-plane/Cargo.toml"
  "aitp-observability/Cargo.toml"
  "kelan-sdk/Cargo.toml"
)

for CRATE in "${CRATES[@]}"; do
  if [ -f "$CRATE" ]; then
    # Replace the first `version = "x.y.z"` line (the crate's own version, not deps)
    sed -i.bak '0,/^version = ".*"/{s/^version = ".*"/version = "'"${VERSION}"'"/}' "$CRATE"
    rm -f "${CRATE}.bak"
    echo "  updated ${CRATE}"
  fi
done

# Also update workspace.package version
sed -i.bak 's/^version = ".*"/version = "'"${VERSION}"'"/' Cargo.toml
rm -f Cargo.toml.bak

# ── Regenerate Cargo.lock
echo "Updating Cargo.lock..."
cargo update --workspace --quiet

# ── Verify build
echo "Verifying build (all workspace crates)..."
cargo build --workspace --quiet || { echo "ERROR: Build failed. Fix errors and try again."; exit 1; }
echo "  ✓ Build succeeded"

# ── Run tests
echo "Running test suite..."
cargo test --workspace --quiet || { echo "ERROR: Tests failed. Fix them and retry."; exit 1; }
echo "  ✓ All tests passed"

# ── Commit version bump
echo "Committing version bump..."
git add -A
git commit -m "chore: bump version to ${VERSION} for release ${TAG}"

# ── Create annotated tag
git tag -a "$TAG" -m "Release ${TAG}

Automated release commit generated by scripts/release.sh"

echo ""
echo "Tag ${TAG} created locally."
echo ""
echo "Pushing will trigger GitHub Actions to build binaries for:"
echo "  • linux-x86_64   • linux-arm64"
echo "  • macos-x86_64   • macos-arm64"
echo "  • windows-x86_64"
echo ""
echo "Watch at: https://github.com/kelan-security/kelan-core/actions"
echo ""

read -r -p "Push ${TAG} to origin now? [y/N] " REPLY
echo ""

if [[ "$REPLY" =~ ^[Yy]$ ]]; then
  git push origin "$BRANCH"
  git push origin "$TAG"
  echo ""
  echo "✓ Release ${TAG} triggered!"
  echo ""
  echo "Release page: https://github.com/kelan-security/kelan-core/releases/tag/${TAG}"
else
  echo "Not pushed. To push manually:"
  echo "  git push origin ${BRANCH} && git push origin ${TAG}"
fi
